version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: bioCard-postgres
    environment:
      POSTGRES_USER: setab
      POSTGRES_PASSWORD: setab123
      POSTGRES_DB: bioCard
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
